  # Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0f2dad9ef09a47e618f180f7eed5a399"
name = "dreamshot-model-mims"
application_url = "https://shopify-model-swap-mims.vercel.app"
embedded = true
handle = "dreamshot-model-mims"

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/orders-paid"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app/subscriptions_update"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_files,write_products,write_pixels,write_script_tags"

[auth]
redirect_urls = [
  "https://shopify-model-swap-mims.vercel.app/auth/callback",
  "https://shopify-model-swap-mims.vercel.app/auth/shopify/callback",
  "https://shopify-model-swap-mims.vercel.app/api/auth/callback"
]

[app_proxy]
url = "https://shopify-model-swap-mims.vercel.app"
subpath = "model-swap"
prefix = "apps"

[pos]
embedded = false
