name: Prisma DB Push

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  push-schema:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    if: ${{ env.DATABASE_URL != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Install deps
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Push schema to database
        run: npx prisma db push
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}

  skip-push:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    if: ${{ env.DATABASE_URL == '' }}
    steps:
      - name: Skip schema push
        run: echo "DATABASE_URL not set. Skipping db push."
